package:
  name: odes
  version: "2.2.1"

source:
  git_rev: 8eea68ff25ab1eae1cc4a8b72337b4f1b7899709
  git_url: https://github.com/logicabrity/odes.git

requirements:
  build:
    - sundials
    - python
    - cython
    - nomkl
    - numpy
    - scipy
    - enum34

  run:
    - sundials
    - python
    - cython
    - nomkl
    - numpy
    - scipy
    - enum34

test:
  requires:
    - nose

about:
  home: https://github.com/logicabrity/odes
  license: New BSD License
  license_file: LICENSE.txt
