package:
  name: odes
  version: "2.2.1"

source:
  git_rev: f3e01e9447e412b22ca2353a632ea554fe437575
  git_url: https://github.com/logicabrity/odes.git

requirements:
  build:
    - sundials
    - python
    - cython
    - nomkl
    - numpy
    - scipy
    - pkgconfig
    - enum34

  run:
    - sundials
    - python
    - cython
    - nomkl
    - numpy
    - scipy
    - enum34
    - nose

about:
  home: https://github.com/logicabrity/odes
  license: New BSD License
  license_file: LICENSE.txt
